[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
"SimSessionH8-300HN" 
[CONFIGURATIONS]
"ANVR10M" 
"ANVR15M" 
"ANVR20M" 
"ANVR30M" 
"ANVR5M" 
"Debug" 
"NA28Release" 
"NL52R10" 
"NL52R15" 
"NL52R20" 
"NL52R30" 
"NL52R5" 
"NL52RIT" 
"Release" 
[CURRENT_CONFIGURATION]
"NL52R5" 
[CURRENT_SESSION]
"DefaultSession" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_ANVR10M]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_ANVR10M]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_ANVR15M]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_ANVR15M]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_ANVR20M]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_ANVR20M]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_ANVR30M]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_ANVR30M]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_ANVR5M]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_ANVR5M]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Debug]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_NA28Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_NA28Release]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_NL52R10]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_NL52R10]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_NL52R15]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_NL52R15]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_NL52R20]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_NL52R20]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_NL52R30]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_NL52R30]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_NL52R5]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_NL52R5]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_NL52RIT]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_NL52RIT]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Release]
"DefaultSession" 
"SimSessionH8-300HN" 
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR15M_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR15M_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR5M_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR10M_DefaultSession]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52RIT_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52RIT_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R30_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R10_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R15_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R5_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_NA28Release_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR30M_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR30M_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R5_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R15_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NA28Release_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR20M_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R30_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R20_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR10M_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R10_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_NL52R20_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR5M_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_ANVR20M_DefaultSession]
[GENERAL_DATA_SESSION_SimSessionH8-300HN]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_SimSessionH8-300HN]
[END]
